language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update
    - sudo apt-get -y install pkg-config libglib2.0-0 libglib2.0-dev
script:
    - make CC="$CC"
    - ./clangsay --version
    - ./clangsay --help
    - make clean
